export enum ItemType {
  HEALING = 'HEALING',
  WEAPON = 'WEAPON',
  ARMOR = 'ARMOR',
  AMULET = 'AMULET',
  CARD = 'CARD',
  QUEST = 'QUEST',
  AMMO = 'AMMO',
  USABLE = 'USABLE',
  MISCELLANEOUS = 'MISCELLANEOUS',
}
