// jobSpritesMap.ts
export const jobSprites: Record<string, string> = {
    "1": "/jobs/novice/NOVICE.gif",
    "2": "/jobs/firstclass/SWORDMAN.gif",
    "3": "/jobs/firstclass/ARCHER.gif",
    "4": "/jobs/firstclass/MAGICIAN.gif",
    "5": "/jobs/firstclass/MERCHANT.gif",
    "6": "/jobs/firstclass/THIEF.gif",
    "7": "/jobs/firstclass/ACOLYTE.gif",
    "8": "/jobs/novice/SUPERNOVICE.gif",
    "9": "/jobs/firstclass/HUNTER.gif",
    "10": "/jobs/firstclass/CHICKEN.gif",
    "11": "/jobs/secondclass/expanded/NINJA.gif",
    "12": "/jobs/secondclass/ALCHEMIST.gif",
    "13": "/jobs/secondclass/ASSASSIN.gif",
    "14": "/jobs/secondclass/BARD.gif",
    "15": "/jobs/secondclass/BLACKSMITH.gif",
    "16": "/jobs/secondclass/CRUSADER.gif",
    "17": "/jobs/secondclass/DANCER.gif",
    "18": "/jobs/secondclass/GUNSLINGER.gif",
    "19": "/jobs/secondclass/KNIGHT.gif",
    "20": "/jobs/secondclass/MONK.gif",
    "21": "/jobs/secondclass/PRIEST.gif",
    "22": "/jobs/secondclass/ROGUE.gif",
    "23": "/jobs/secondclass/SAGE.gif",
    "24": "/jobs/secondclass/WIZARD.gif",
  };

  export const jobGenderSprites: Record<string, string> = {
    "1": "/jobgender/novice/NOVICE",
    "2": "/jobgender/firstclass/SWORDMAN",
    "3": "/jobgender/firstclass/ARCHER",
    "4": "/jobgender/firstclass/MAGICIAN",
    "5": "/jobgender/firstclass/MERCHANT",
    "6": "/jobgender/firstclass/THIEF",
    "7": "/jobgender/firstclass/ACOLYTE",
    "8": "/jobgender/novice/SUPERNOVICE",
    "9": "/jobgender/firstclass/HUNTER",
    "10": "/jobgender/firstclass/CHICKEN",
    "11": "/jobgender/secondclass/expanded/NINJA",
    "12": "/jobgender/secondclass/ALCHEMIST.gif",
    "13": "/jobgender/secondclass/ASSASSIN.gif",
    "14": "/jobgender/secondclass/BARD.gif",
    "15": "/jobgender/secondclass/BLACKSMITH.gif",
    "16": "/jobgender/secondclass/CRUSADER.gif",
    "17": "/jobgender/secondclass/DANCER.gif",
    "18": "/jobgender/secondclass/GUNSLINGER.gif",
    "19": "/jobgender/secondclass/KNIGHT.gif",
    "20": "/jobgender/secondclass/MONK.gif",
    "21": "/jobgender/secondclass/PRIEST.gif",
    "22": "/jobgender/secondclass/ROGUE.gif",
    "23": "/jobgender/secondclass/SAGE.gif",
    "24": "/jobgender/secondclass/WIZARD.gif",
  };
  
  