import { EquipmentSlot } from "@/types/Enums/EquipmentSlotEnum";
import { ItemType } from "@/types/Enums/ItemTypeEnum";
import { EquipmentItem } from "@/types/EquipmentItem";
import { InventoryItem } from "@/types/InventoryItem";
import { ItemInstance } from "@/types/ItemInstance";
import { JobName } from "@/types/Enums/JobNameEnum";
import { MonsterDrop } from "@/types/MonsterDrop";
import { Recipe } from "@/types/Recipe";
import { StorageItem } from "@/types/StorageItem";
import { ElementType } from "react";

export type Item = {
  id: number;
  name: string;
  type: ItemType;
  jobRequired?: JobName;
  description: string;
  buyPrice: number;
  sellPrice: number;
  weight: number;
  attack?: number;
  magicAttack?: number;
  defense?: number;
  magicDefense?: number;
  requiredLevel?: number;
  slot?: number;
  equipSlots: EquipmentSlot[];
  script?: string;
  isStackable: boolean;
  maxStack: number;
  isTradable: boolean;
  isConsumable: boolean;
  element: ElementType;
  cardSlots?: number;
  sprite?: string;
  recipes: Recipe[];
  inventoryItems: InventoryItem[];
  storageItems: StorageItem[];
  equipmentItems: EquipmentItem[];
  drops: MonsterDrop[];
  instances: ItemInstance[];
};