export async function jobClassSeed(prisma) {
  const jobClass = [
    {
      id: 1,
      name: "Novice",
      str: 1,
      agi: 1,
      vit: 1,
      int: 1,
      dex: 1,
      luk: 1,
      health: 40,
      mana: 10,
      maxHealth: 40,
      maxMana: 10,
      attackPower: 10,
      magicPower: 0,
      defense: 2,
      magicDefense: 1,
      baseLevel: 1,
      jobLevel: 1,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 10,
      maxJobExp: 10,
      skillPoints: 0
    },
    {
      id: 2,
      name: "Swordsman",
      str: 5,
      agi: 3,
      vit: 4,
      int: 1,
      dex: 2,
      luk: 1,
      health: 80,
      mana: 20,
      maxHealth: 80,
      maxMana: 20,
      attackPower: 20,
      magicPower: 0,
      defense: 5,
      magicDefense: 2,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 3,
      name: "Archer",
      str: 3,
      agi: 7,
      vit: 2,
      int: 1,
      dex: 6,
      luk: 1,
      health: 60,
      mana: 20,
      maxHealth: 60,
      maxMana: 20,
      attackPower: 15,
      magicPower: 0,
      defense: 3,
      magicDefense: 2,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 4,
      name: "Mage",
      str: 2,
      agi: 3,
      vit: 2,
      int: 7,
      dex: 4,
      luk: 1,
      health: 50,
      mana: 40,
      maxHealth: 50,
      maxMana: 40,
      attackPower: 5,
      magicPower: 30,
      defense: 2,
      magicDefense: 5,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 5,
      name: "Merchant",
      str: 4,
      agi: 2,
      vit: 3,
      int: 2,
      dex: 5,
      luk: 1,
      health: 70,
      mana: 20,
      maxHealth: 70,
      maxMana: 20,
      attackPower: 12,
      magicPower: 0,
      defense: 4,
      magicDefense: 2,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 6,
      name: "Thief",
      str: 3,
      agi: 8,
      vit: 2,
      int: 1,
      dex: 6,
      luk: 2,
      health: 55,
      mana: 20,
      maxHealth: 55,
      maxMana: 20,
      attackPower: 15,
      magicPower: 0,
      defense: 3,
      magicDefense: 1,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 7,
      name: "Acolyte",
      str: 3,
      agi: 2,
      vit: 4,
      int: 6,
      dex: 3,
      luk: 2,
      health: 70,
      mana: 30,
      maxHealth: 70,
      maxMana: 30,
      attackPower: 7,
      magicPower: 10,
      defense: 4,
      magicDefense: 4,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 8,
      name: "Super Novice",
      str: 3,
      agi: 3,
      vit: 3,
      int: 3,
      dex: 3,
      luk: 3,
      health: 60,
      mana: 25,
      maxHealth: 60,
      maxMana: 25,
      attackPower: 12,
      magicPower: 10,
      defense: 4,
      magicDefense: 3,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 9,
      name: "Hunter",
      str: 4,
      agi: 8,
      vit: 3,
      int: 1,
      dex: 7,
      luk: 2,
      health: 80,
      mana: 30,
      maxHealth: 80,
      maxMana: 30,
      attackPower: 20,
      magicPower: 0,
      defense: 4,
      magicDefense: 3,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 10,
      name: "Chicken",
      str: 1,
      agi: 2,
      vit: 1,
      int: 1,
      dex: 1,
      luk: 3,
      health: 30,
      mana: 10,
      maxHealth: 30,
      maxMana: 10,
      attackPower: 2,
      magicPower: 0,
      defense: 1,
      magicDefense: 1,
      baseLevel: 1,
      jobLevel: 1,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 10,
      maxJobExp: 10,
      skillPoints: 0
    },
    {
      id: 11,
      name: "Ninja",
      str: 5,
      agi: 7,
      vit: 4,
      int: 3,
      dex: 6,
      luk: 3,
      health: 100,
      mana: 40,
      maxHealth: 100,
      maxMana: 40,
      attackPower: 25,
      magicPower: 15,
      defense: 6,
      magicDefense: 4,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 12,
      name: "Alchemist",
      str: 4,
      agi: 3,
      vit: 4,
      int: 7,
      dex: 5,
      luk: 2,
      health: 75,
      mana: 40,
      maxHealth: 75,
      maxMana: 40,
      attackPower: 12,
      magicPower: 20,
      defense: 5,
      magicDefense: 5,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 13,
      name: "Assassin",
      str: 5,
      agi: 8,
      vit: 3,
      int: 1,
      dex: 6,
      luk: 3,
      health: 85,
      mana: 20,
      maxHealth: 85,
      maxMana: 20,
      attackPower: 20,
      magicPower: 0,
      defense: 5,
      magicDefense: 3,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 14,
      name: "Bard",
      str: 3,
      agi: 4,
      vit: 3,
      int: 6,
      dex: 5,
      luk: 2,
      health: 70,
      mana: 35,
      maxHealth: 70,
      maxMana: 35,
      attackPower: 12,
      magicPower: 20,
      defense: 4,
      magicDefense: 4,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 15,
      name: "Blacksmith",
      str: 6,
      agi: 3,
      vit: 5,
      int: 2,
      dex: 7,
      luk: 2,
      health: 90,
      mana: 25,
      maxHealth: 90,
      maxMana: 25,
      attackPower: 22,
      magicPower: 0,
      defense: 6,
      magicDefense: 3,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 16,
      name: "Crusader",
      str: 7,
      agi: 4,
      vit: 6,
      int: 3,
      dex: 5,
      luk: 2,
      health: 110,
      mana: 30,
      maxHealth: 110,
      maxMana: 30,
      attackPower: 25,
      magicPower: 10,
      defense: 8,
      magicDefense: 4,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 17,
      name: "Dancer",
      str: 3,
      agi: 6,
      vit: 3,
      int: 4,
      dex: 6,
      luk: 4,
      health: 70,
      mana: 35,
      maxHealth: 70,
      maxMana: 35,
      attackPower: 15,
      magicPower: 10,
      defense: 4,
      magicDefense: 3,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 18,
      name: "Gunslinger",
      str: 5,
      agi: 6,
      vit: 3,
      int: 2,
      dex: 8,
      luk: 3,
      health: 80,
      mana: 30,
      maxHealth: 80,
      maxMana: 30,
      attackPower: 18,
      magicPower: 0,
      defense: 5,
      magicDefense: 2,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 19,
      name: "Knight",
      str: 7,
      agi: 3,
      vit: 7,
      int: 1,
      dex: 5,
      luk: 2,
      health: 120,
      mana: 20,
      maxHealth: 120,
      maxMana: 20,
      attackPower: 30,
      magicPower: 0,
      defense: 9,
      magicDefense: 4,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 20,
      name: "Monk",
      str: 6,
      agi: 4,
      vit: 5,
      int: 3,
      dex: 4,
      luk: 4,
      health: 100,
      mana: 30,
      maxHealth: 100,
      maxMana: 30,
      attackPower: 25,
      magicPower: 15,
      defense: 7,
      magicDefense: 5,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 21,
      name: "Priest",
      str: 3,
      agi: 2,
      vit: 5,
      int: 7,
      dex: 4,
      luk: 3,
      health: 75,
      mana: 40,
      maxHealth: 75,
      maxMana: 40,
      attackPower: 8,
      magicPower: 25,
      defense: 4,
      magicDefense: 6,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 22,
      name: "Rogue",
      str: 4,
      agi: 7,
      vit: 3,
      int: 2,
      dex: 6,
      luk: 4,
      health: 75,
      mana: 20,
      maxHealth: 75,
      maxMana: 20,
      attackPower: 18,
      magicPower: 0,
      defense: 5,
      magicDefense: 3,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 23,
      name: "Sage",
      str: 3,
      agi: 3,
      vit: 3,
      int: 8,
      dex: 5,
      luk: 2,
      health: 60,
      mana: 50,
      maxHealth: 60,
      maxMana: 50,
      attackPower: 6,
      magicPower: 30,
      defense: 3,
      magicDefense: 7,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    },
    {
      id: 24,
      name: "Wizard",
      str: 2,
      agi: 2,
      vit: 3,
      int: 10,
      dex: 5,
      luk: 2,
      health: 50,
      mana: 60,
      maxHealth: 50,
      maxMana: 60,
      attackPower: 5,
      magicPower: 40,
      defense: 2,
      magicDefense: 8,
      baseLevel: 10,
      jobLevel: 10,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 50,
      maxJobExp: 50,
      skillPoints: 1
    }
  ];

  for (let i = 0; i < jobClass.length; i++) {
    const existingJobClass = await prisma.jobClass.findUnique({
      where: { name: jobClass[i].name },
    });

    if (!existingJobClass) {
      await prisma.jobClass.create({
        data: jobClass[i],
      });

    } else {
      console.log(`JobClass ${jobClass[i].name} ya existe.`);
    }
  }

  await prisma.$disconnect();
}
