// monsterSeed.js

/**
 * Siembra algunos monstruos básicos en la base de datos.
 * Asegúrate de que este seeder se ejecute ANTES que los spawns y drops, 
 * ya que ellos dependen de los monsters.
 */
export async function monsterSeed(prisma) {
  const monstersData = [
      {
    name: 'Poring',
    level: 1,
    health: 50,
    mana: 10,
    baseExp: 10,
    jobExp: 5,
    attack: 1,
    magicAttack: 1,
    defense: 1,
    magicDefense: 1,
    attackSpeed: 1,
    moveSpeed: 1,
    attackRange: 1,
    element: 'NEUTRAL',
    size: 'Small',
    race: 'Slime',
    sprite: 'poring.png'
  },
  {
    name: 'Lunatic',
    level: 10,
    health: 500,
    mana: 100,
    baseExp: 100,
    jobExp: 100,
    attack: 20,
    magicAttack: 10,
    defense: 15,
    magicDefense: 10,
    attackSpeed: 2,
    moveSpeed: 2,
    attackRange: 1,
    element: 'WIND',
    size: 'Medium',
    race: 'Undead',
    sprite: 'lunatic.png'
  },
  {
    name: 'Poporing',
    level: 5,
    health: 200,
    mana: 30,
    baseExp: 30,
    jobExp: 15,
    attack: 5,
    magicAttack: 3,
    defense: 5,
    magicDefense: 3,
    attackSpeed: 1,
    moveSpeed: 1,
    attackRange: 1,
    element: 'NEUTRAL',
    size: 'Small',
    race: 'Slime',
    sprite: 'poporing.png'
  },
  {
    name: 'Drops',
    level: 7,
    health: 300,
    mana: 50,
    baseExp: 50,
    jobExp: 25,
    attack: 8,
    magicAttack: 5,
    defense: 6,
    magicDefense: 4,
    attackSpeed: 1,
    moveSpeed: 1,
    attackRange: 1,
    element: 'WATER',
    size: 'Small',
    race: 'Slime',
    sprite: 'drops.png'
  },
  {
    name: 'Marin',
    level: 12,
    health: 600,
    mana: 120,
    baseExp: 120,
    jobExp: 60,
    attack: 25,
    magicAttack: 15,
    defense: 20,
    magicDefense: 12,
    attackSpeed: 2,
    moveSpeed: 2,
    attackRange: 1,
    element: 'WATER',
    size: 'Medium',
    race: 'Fish',
    sprite: 'marin.png'
  },
  {
    name: 'Zombie',
    level: 15,
    health: 800,
    mana: 150,
    baseExp: 150,
    jobExp: 75,
    attack: 30,
    magicAttack: 10,
    defense: 25,
    magicDefense: 15,
    attackSpeed: 2,
    moveSpeed: 1,
    attackRange: 1,
    element: 'DARK',
    size: 'Medium',
    race: 'Undead',
    sprite: 'zombie.png'
  },
  {
    name: 'Archer Skeleton',
    level: 20,
    health: 1000,
    mana: 200,
    baseExp: 200,
    jobExp: 100,
    attack: 40,
    magicAttack: 20,
    defense: 30,
    magicDefense: 20,
    attackSpeed: 3,
    moveSpeed: 2,
    attackRange: 5,
    element: 'DARK',
    size: 'Medium',
    race: 'Undead',
    sprite: 'archer_skeleton.png'
  },
  {
    name: 'Orc',
    level: 25,
    health: 1500,
    mana: 250,
    baseExp: 250,
    jobExp: 125,
    attack: 50,
    magicAttack: 10,
    defense: 40,
    magicDefense: 20,
    attackSpeed: 2,
    moveSpeed: 2,
    attackRange: 1,
    element: 'FIRE',
    size: 'Large',
    race: 'Demi-Human',
    sprite: 'orc.png'
  },
  {
    name: 'Mummy',
    level: 30,
    health: 2000,
    mana: 300,
    baseExp: 300,
    jobExp: 150,
    attack: 60,
    magicAttack: 30,
    defense: 50,
    magicDefense: 30,
    attackSpeed: 2,
    moveSpeed: 1,
    attackRange: 1,
    element: 'DARK',
    size: 'Medium',
    race: 'Undead',
    sprite: 'mummy.png'
  },
  {
    name: 'Golem',
    level: 35,
    health: 3000,
    mana: 400,
    baseExp: 400,
    jobExp: 200,
    attack: 70,
    magicAttack: 10,
    defense: 60,
    magicDefense: 40,
    attackSpeed: 1,
    moveSpeed: 1,
    attackRange: 1,
    element: 'EARTH',
    size: 'Large',
    race: 'Formless',
    sprite: 'golem.png'
  },
  {
    name: 'Harpy',
    level: 40,
    health: 2500,
    mana: 350,
    baseExp: 350,
    jobExp: 175,
    attack: 65,
    magicAttack: 40,
    defense: 45,
    magicDefense: 35,
    attackSpeed: 3,
    moveSpeed: 3,
    attackRange: 1,
    element: 'WIND',
    size: 'Medium',
    race: 'Brute',
    sprite: 'harpy.png'
  }
  ];

  for (const monsterData of monstersData) {
    await prisma.monster.create({
      data: monsterData,
    });
  }
}
