export async function jobClassSeed(prisma) {
  const jobClass = [
    {
      name: "Novice",
      str: 1,
      agi: 1,
      vit: 1,
      int: 1,
      dex: 1,
      luk: 1,
      health: 40,
      mana: 10,
      maxHealth: 40,
      maxMana: 10,
      attackPower: 10,
      magicPower: 0,
      defense: 2,
      magicDefense: 1,
      baseLevel: 1,
      jobLevel: 1,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 10,
      maxJobExp: 10,
      skillPoints: 0,
    },
    {
      name: "Swordsman",
      str: 5,
      agi: 1,
      vit: 3,
      int: 1,
      dex: 2,
      luk: 1,
      health: 50,
      mana: 10,
      maxHealth: 40,
      maxMana: 10,
      attackPower: 15,
      magicPower: 0,
      defense: 5,
      magicDefense: 1,
      baseLevel: 1,
      jobLevel: 1,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 10,
      maxJobExp: 10,
      skillPoints: 0,
    },
    {
      name: "Mage",
      str: 1,
      agi: 1,
      vit: 1,
      int: 5,
      dex: 2,
      luk: 1,
      health: 40,
      mana: 20,
      maxHealth: 40,
      maxMana: 10,
      attackPower: 0,
      magicPower: 15,
      defense: 2,
      magicDefense: 5,
      baseLevel: 1,
      jobLevel: 1,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 10,
      maxJobExp: 10,
      skillPoints: 0,
    },
    {
      name: "Archer",
      str: 1,
      agi: 5,
      vit: 1,
      int: 1,
      dex: 3,
      luk: 1,
      health: 40,
      mana: 10,
      maxHealth: 40,
      maxMana: 10,
      attackPower: 10,
      magicPower: 0,
      defense: 2,
      magicDefense: 1,
      baseLevel: 1,
      jobLevel: 1,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 10,
      maxJobExp: 10,
      skillPoints: 0,
    },
    {
      name: "Thief",
      str: 1,
      agi: 5,
      vit: 1,
      int: 1,
      dex: 3,
      luk: 1,
      health: 40,
      mana: 10,
      maxHealth: 40,
      maxMana: 10,
      attackPower: 10,
      magicPower: 0,
      defense: 2,
      magicDefense: 1,
      baseLevel: 1,
      jobLevel: 1,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 10,
      maxJobExp: 10,
      skillPoints: 0,
    },
    {
      name: "Acolyte",
      str: 1,
      agi: 5,
      vit: 1,
      int: 1,
      dex: 3,
      luk: 1,
      health: 40,
      mana: 10,
      maxHealth: 40,
      maxMana: 10,
      attackPower: 10,
      magicPower: 0,
      defense: 2,
      magicDefense: 1,
      baseLevel: 1,
      jobLevel: 1,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 10,
      maxJobExp: 10,
      skillPoints: 0,
    },
    {
      name: "Merchant",
      str: 1,
      agi: 5,
      vit: 1,
      int: 1,
      dex: 3,
      luk: 1,
      health: 40,
      mana: 10,
      maxHealth: 40,
      maxMana: 10,
      attackPower: 10,
      magicPower: 0,
      defense: 2,
      magicDefense: 1,
      baseLevel: 1,
      jobLevel: 1,
      baseExp: 0,
      jobExp: 0,
      maxBaseExp: 10,
      maxJobExp: 10,
      skillPoints: 0,
    },
  ];

  for (let i = 0; i < jobClass.length; i++) {
    const existingJobClass = await prisma.jobClass.findUnique({
      where: { name: jobClass[i].name },
    });

    if (!existingJobClass) {
      await prisma.jobClass.create({
        data: jobClass[i],
      });
      console.log(`JobClass ${jobClass[i].name} creado.✅`);
    } else {
      console.log(`JobClass ${jobClass[i].name} ya existe. ✅`);
    }
  }
}
