// jobSpritesMap.ts
export const jobSprites: Record<string, string> = {
  "NOVICE": "/jobs/novice/NOVICE",
  "SWORDSMAN": "/jobs/firstclass/SWORDMAN",
  "ARCHER": "/jobs/firstclass/ARCHER",
  "MAGICIAN": "/jobs/firstclass/MAGICIAN",
  "MERCHANT": "/jobs/firstclass/MERCHANT",
  "THIEF": "/jobs/firstclass/THIEF",
  "ACOLYTE": "/jobs/firstclass/ACOLYTE",
  "SUPERNOVICE": "/jobs/novice/SUPERNOVICE",
  "HUNTER": "/jobs/firstclass/HUNTER",
  "CHICKEN": "/jobs/firstclass/CHICKEN",
  "NINJA": "/jobs/secondclass/expanded/NINJA",
  "ALCHEMIST": "/jobs/secondclass/ALCHEMIST",
  "ASSASSIN": "/jobs/secondclass/ASSASSIN",
  "BARD": "/jobs/secondclass/BARD",
  "BLACKSMITH": "/jobs/secondclass/BLACKSMITH",
  "CRUSADER": "/jobs/secondclass/CRUSADER",
  "DANCER": "/jobs/secondclass/DANCER",
  "GUNSLINGER": "/jobs/secondclass/GUNSLINGER",
  "KNIGHT": "/jobs/secondclass/KNIGHT",
  "MONK": "/jobs/secondclass/MONK",
  "PRIEST": "/jobs/secondclass/PRIEST",
  "ROGUE": "/jobs/secondclass/ROGUE",
  "SAGE": "/jobs/secondclass/SAGE",
  "WIZARD": "/jobs/secondclass/WIZARD",
};

export const jobGenderSprites: Record<string, string> = {
  "NOVICE": "/jobgender/novice/NOVICE",
  "SWORDSMAN": "/jobgender/firstclass/SWORDMAN",
  "ARCHER": "/jobgender/firstclass/ARCHER",
  "MAGICIAN": "/jobgender/firstclass/MAGICIAN",
  "MERCHANT": "/jobgender/firstclass/MERCHANT",
  "THIEF": "/jobgender/firstclass/THIEF",
  "ACOLYTE": "/jobgender/firstclass/ACOLYTE",
  "SUPERNOVICE": "/jobgender/novice/SUPERNOVICE",
  "HUNTER": "/jobgender/firstclass/HUNTER",
  "CHICKEN": "/jobgender/firstclass/CHICKEN",
  "NINJA": "/jobgender/secondclass/expanded/NINJA",
  "ALCHEMIST": "/jobgender/secondclass/ALCHEMIST",
  "ASSASSIN": "/jobgender/secondclass/ASSASSIN",
  "BARD": "/jobgender/secondclass/BARD",
  "BLACKSMITH": "/jobgender/secondclass/BLACKSMITH",
  "CRUSADER": "/jobgender/secondclass/CRUSADER",
  "DANCER": "/jobgender/secondclass/DANCER",
  "GUNSLINGER": "/jobgender/secondclass/GUNSLINGER",
  "KNIGHT": "/jobgender/secondclass/KNIGHT",
  "MONK": "/jobgender/secondclass/MONK",
  "PRIEST": "/jobgender/secondclass/PRIEST",
  "ROGUE": "/jobgender/secondclass/ROGUE",
  "SAGE": "/jobgender/secondclass/SAGE",
  "WIZARD": "/jobgender/secondclass/WIZARD",
};
